-- 스프링 부트는 SQL 스크립트를 실행해서 애플리케이션 로딩 시점에 데이터베이스를 초기화하는 기능을 지원해줌
-- 해당 루트(test > resources > schema.sql 이어야함) 안에 초기화할 테이블의 정보를 적어주기만 하면 됨.
drop table if exists item CASCADE;
create table item
(
 id bigint generated by default as identity,
 item_name varchar(10),
 price integer,
 quantity integer,
 primary key (id)
);